# Generated by Django 5.2.1 on 2025-05-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagipost', '0002_post_created_at_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
